FROM mcr.microsoft.com/devcontainers/typescript-node:22

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Install global node modules
RUN su node -c "npm install -g pnpm @google/gemini-cli@latest"
